apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluxcd-helm-upgrader
  labels:
    app.kubernetes.io/name: fluxcd-helm-upgrader
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fluxcd-helm-upgrader
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fluxcd-helm-upgrader
    spec:
      serviceAccountName: fluxcd-helm-upgrader
      containers:
        - name: app
          image: kenchrcum/fluxcd-helm-upgrader:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: LOG_LEVEL
              value: "INFO"
            - name: INTERVAL_SECONDS
              value: "300"
            - name: INCLUDE_PRERELEASE
              value: "false"
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi
