apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fluxcd-helm-upgrader.fullname" . }}
  labels:
    {{- include "fluxcd-helm-upgrader.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "fluxcd-helm-upgrader.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "fluxcd-helm-upgrader.labels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ default (include "fluxcd-helm-upgrader.fullname" .) .Values.serviceAccount.name }}
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LOG_LEVEL
              value: {{ .Values.logLevel | quote }}
            - name: INTERVAL_SECONDS
              value: {{ .Values.intervalSeconds | quote }}
            - name: INCLUDE_PRERELEASE
              value: {{ .Values.includePrerelease | quote }}
            - name: REPO_URL
              value: {{ .Values.repo.url | quote }}
            - name: REPO_BRANCH
              value: {{ .Values.repo.branch | quote }}
            - name: REPO_SEARCH_PATTERN
              value: {{ .Values.repo.searchPattern | quote }}
            - name: REPO_CLONE_DIR
              value: {{ .Values.repo.cloneDir | quote }}
            {{- if and .Values.repo.githubTokenSecret.enabled .Values.repo.githubTokenSecret.name }}
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.repo.githubTokenSecret.name }}
                  key: {{ default "token" .Values.repo.githubTokenSecret.key | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
